package dev.ynagai.autograph.schema

/**
 * Generates a single Kotlin source file with one `Tracker.track<EventName>(...)` extension
 * function per [events], typed from each event's declared properties. Required properties become
 * non-nullable parameters; optional properties become nullable parameters defaulting to `null` and
 * are omitted from the emitted event when left `null`.
 *
 * `parseTrackingPlan` already rejects colliding function/parameter names, so this function assumes
 * [events] is already validated.
 */
public fun generateTrackerExtensions(events: List<EventSchema>, packageName: String): String = buildString {
    appendLine("// GENERATED by autograph-schema. Do not edit by hand.")
    appendLine("package $packageName")
    appendLine()
    appendLine("import dev.ynagai.autograph.Tracker")
    appendLine("import kotlinx.serialization.json.buildJsonObject")
    appendLine("import kotlinx.serialization.json.put")
    for (event in events) {
        appendLine()
        append(generateFunction(event))
    }
}

private fun generateFunction(event: EventSchema): String {
    // Required parameters first: Kotlin allows a defaulted parameter anywhere, but a positional
    // call can only omit a *trailing* run of defaulted ones.
    val orderedProperties = event.properties.sortedBy { it.required.not() }
    val functionName = "track" + event.name.toPascalCase()

    return buildString {
        appendLine("public fun Tracker.$functionName(")
        for (property in orderedProperties) {
            val paramName = property.name.toCamelCase()
            val paramType = if (property.required) property.type.kotlinType else "${property.type.kotlinType}?"
            val default = if (property.required) "" else " = null"
            appendLine("    $paramName: $paramType$default,")
        }
        appendLine(") {")
        appendLine("    track(")
        appendLine("        \"${event.name.escapeKotlinStringLiteral()}\",")
        appendLine("        buildJsonObject {")
        for (property in event.properties) {
            val paramName = property.name.toCamelCase()
            if (property.required) {
                appendLine("            put(\"${property.name.escapeKotlinStringLiteral()}\", $paramName)")
            } else {
                appendLine("            $paramName?.let { put(\"${property.name.escapeKotlinStringLiteral()}\", it) }")
            }
        }
        appendLine("        },")
        appendLine("    )")
        append("}")
    }
}
