package dev.ynagai.autograph.schema

import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertTrue

class TrackerCodegenTest {

    @Test
    fun generatesAFunctionPerEventWithRequiredThenOptionalParameters() {
        val events = listOf(
            EventSchema(
                "Recipe Saved",
                listOf(
                    PropertySchema("quantity", PropertyType.INTEGER, required = false),
                    PropertySchema("target", PropertyType.STRING, required = true),
                ),
            ),
        )

        val source = generateTrackerExtensions(events, "com.example.generated")

        assertEquals(
            """
            // GENERATED by autograph-schema. Do not edit by hand.
            package com.example.generated

            import dev.ynagai.autograph.Tracker
            import kotlinx.serialization.json.buildJsonObject
            import kotlinx.serialization.json.put

            public fun Tracker.trackRecipeSaved(
                target: String,
                quantity: Long? = null,
            ) {
                track(
                    "Recipe Saved",
                    buildJsonObject {
                        quantity?.let { put("quantity", it) }
                        put("target", target)
                    },
                )
            }
            """.trimIndent(),
            source,
        )
    }

    @Test
    fun generatesAZeroParameterFunctionForAnEventWithNoProperties() {
        val source = generateTrackerExtensions(listOf(EventSchema("App Opened", emptyList())), "p")

        assertTrue(source.contains("public fun Tracker.trackAppOpened(\n) {"))
        assertTrue(source.contains("\"App Opened\""))
    }

    @Test
    fun escapesQuotesAndBackslashesInEventAndPropertyNames() {
        val events = listOf(
            EventSchema(
                """Say "Hi"""",
                listOf(PropertySchema("""quote"prop""", PropertyType.STRING, required = true)),
            ),
        )

        val source = generateTrackerExtensions(events, "p")

        assertTrue(source.contains(""""Say \"Hi\""""".trimIndent()))
        assertTrue(source.contains("""put("quote\"prop", """))
    }

    @Test
    fun escapesDollarSignsInEventAndPropertyNamesSoTheyAreNotTemplateInterpolation() {
        val events = listOf(
            EventSchema(
                "User \$id Set",
                listOf(PropertySchema("cost\$usd", PropertyType.STRING, required = true)),
            ),
        )

        val source = generateTrackerExtensions(events, "p")

        assertTrue(source.contains("\"User \\\$id Set\""))
        assertTrue(source.contains("put(\"cost\\\$usd\", "))
    }

    @Test
    fun backtickEscapesAParameterNameThatIsAKotlinHardKeyword() {
        val events = listOf(EventSchema("E", listOf(PropertySchema("in", PropertyType.STRING, required = true))))

        val source = generateTrackerExtensions(events, "p")

        assertTrue(source.contains("`in`: String,"), source)
        assertTrue(source.contains("put(\"in\", `in`)"), source)
    }

    @Test
    fun backtickEscapesAParameterNameThatStartsWithADigit() {
        val events = listOf(EventSchema("E", listOf(PropertySchema("2fa_enabled", PropertyType.BOOLEAN, required = false))))

        val source = generateTrackerExtensions(events, "p")

        assertTrue(source.contains("`2faEnabled`: Boolean? = null,"), source)
        assertTrue(source.contains("`2faEnabled`?.let { put(\"2fa_enabled\", it) }"), source)
    }

    @Test
    fun distinctEventsProduceDistinctFunctionsInOneFile() {
        val events = listOf(
            EventSchema("A", emptyList()),
            EventSchema("B", emptyList()),
        )

        val source = generateTrackerExtensions(events, "p")

        assertTrue(source.contains("fun Tracker.trackA("))
        assertTrue(source.contains("fun Tracker.trackB("))
    }
}
